// Generated by scripts/generate.mjs from lucide-react@1.0.0 (ISC). Do not edit.
import { createLucideIcon, type IconNode } from 'lucide-react';

export const __iconNode: IconNode = [
  [
    "path",
    {
      "d": "M10.88 21.94 15.46 14",
      "key": "xkve6t"
    }
  ],
  [
    "path",
    {
      "d": "M21.17 8H12",
      "key": "19dcdn"
    }
  ],
  [
    "path",
    {
      "d": "M3.95 6.06 8.54 14",
      "key": "g8jz9m"
    }
  ],
  [
    "circle",
    {
      "cx": "12",
      "cy": "12",
      "r": "10",
      "key": "1mglay"
    }
  ],
  [
    "circle",
    {
      "cx": "12",
      "cy": "12",
      "r": "4",
      "key": "4exip2"
    }
  ]
];

const Chromium = /* @__PURE__ */ createLucideIcon('chromium', __iconNode);

export default Chromium;
