// Generated by scripts/generate.mjs from lucide-react@1.0.0 (ISC). Do not edit.
import { createLucideIcon, type IconNode } from 'lucide-react';

export const __iconNode: IconNode = [
  [
    "path",
    {
      "d": "M5 16V9h14V2H5l14 14h-7m-7 0 7 7v-7m-7 0h7",
      "key": "1a2nng"
    }
  ]
];

const Framer = /* @__PURE__ */ createLucideIcon('framer', __iconNode);

export default Framer;
