// Generated by scripts/generate.mjs from lucide-react@1.0.0 (ISC). Do not edit.
import { createLucideIcon, type IconNode } from 'lucide-react';

export const __iconNode: IconNode = [
  [
    "path",
    {
      "d": "M20 3a2 2 0 0 1 2 2v6a1 1 0 0 1-20 0V5a2 2 0 0 1 2-2z",
      "key": "1uodqw"
    }
  ],
  [
    "path",
    {
      "d": "m8 10 4 4 4-4",
      "key": "1mxd5q"
    }
  ]
];

const Pocket = /* @__PURE__ */ createLucideIcon('pocket', __iconNode);

export default Pocket;
