// Generated by scripts/generate.mjs from lucide-react@1.0.0 (ISC). Do not edit.
import { createLucideIcon, type IconNode } from 'lucide-react';

export const __iconNode: IconNode = [
  [
    "path",
    {
      "d": "M21 2H3v16h5v4l4-4h5l4-4V2zm-10 9V7m5 4V7",
      "key": "c0yzno"
    }
  ]
];

const Twitch = /* @__PURE__ */ createLucideIcon('twitch', __iconNode);

export default Twitch;
