// Regenerates src/icons/*.ts, src/index.ts, src/nodes.ts, svg/*.svg and cli/names.json from lucide 1.0.0,
// the last release that still shipped brand icons (they were removed in 1.1.0).
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const lucideReactDir = dirname(require.resolve('lucide-react-1.0.0/package.json'));
const lucideStaticDir = dirname(require.resolve('lucide-static-1.0.0/package.json'));

// kebab-case name -> extra aliases (besides <Name>Icon and Lucide<Name>)
const ICONS = {
  chromium: ['Chrome'],
  codepen: [],
  codesandbox: [],
  dribbble: [],
  facebook: [],
  figma: [],
  framer: [],
  github: [],
  gitlab: [],
  instagram: [],
  linkedin: [],
  pocket: [],
  slack: [],
  trello: [],
  twitch: [],
  twitter: [],
  youtube: [],
};

const pascal = (name) => name.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const header = '// Generated by scripts/generate.mjs from lucide-react@1.0.0 (ISC). Do not edit.\n';

await rm(join(root, 'src/icons'), { recursive: true, force: true });
await rm(join(root, 'src/nodes.ts'), { force: true });
await rm(join(root, 'svg'), { recursive: true, force: true });
await mkdir(join(root, 'src/icons'), { recursive: true });
await mkdir(join(root, 'svg'), { recursive: true });
await mkdir(join(root, 'cli'), { recursive: true });

const exportLines = [];
const nodeLines = [];
const componentNames = [];
for (const [name, aliases] of Object.entries(ICONS)) {
  const component = pascal(name);
  const source = pathToFileURL(join(lucideReactDir, `dist/esm/icons/${name}.js`)).href;
  const { __iconNode } = await import(source);

  await writeFile(
    join(root, `src/icons/${name}.ts`),
    `${header}import { createLucideIcon, type IconNode } from 'lucide-react';

export const __iconNode: IconNode = ${JSON.stringify(__iconNode, null, 2)};

const ${component} = /* @__PURE__ */ createLucideIcon('${name}', __iconNode);

export default ${component};
`,
  );

  // Framework-free node (no React `key`), the format `lucide`, `@lucide/svelte` & co. take.
  const node = __iconNode.map(([tag, { key, ...attrs }]) => [tag, attrs]);
  nodeLines.push(
    `export const ${component}: IconNode = ${JSON.stringify(node)};`,
    ...aliases.map((alias) => `export const ${alias} = ${component};`),
  );

  const svg = await readFile(join(lucideStaticDir, `icons/${name}.svg`), 'utf8');
  await writeFile(join(root, `svg/${name}.svg`), svg);

  const names = [component, ...aliases].flatMap((n) => [n, `${n}Icon`, `Lucide${n}`]);
  componentNames.push(...names);
  exportLines.push(
    `export { ${names.map((n) => `default as ${n}`).join(', ')}, __iconNode as ${component.charAt(0).toLowerCase()}${component.slice(1)}IconNode } from './icons/${name}';`,
  );
}

await writeFile(join(root, 'src/index.ts'), `${header}${exportLines.join('\n')}\n`);
await writeFile(
  join(root, 'src/nodes.ts'),
  `${header}// Plain icon nodes with no framework dependency, e.g. for \`createIcons({ icons: { Github } })\` from 'lucide'.
export type IconNode = [tag: string, attrs: Record<string, string>][];

${nodeLines.join('\n')}
`,
);
// Used by the `lucide-brands migrate` CLI to know which lucide-react imports to move.
await writeFile(join(root, 'cli/names.json'), `${JSON.stringify(componentNames.sort(), null, 2)}\n`);
console.log(`Generated ${Object.keys(ICONS).length} icons.`);
